name: Upgrade dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: upgrade-deps
          pr-labels: dependencies
          pr-title: "chore(deps): update dependencies"
          commit-msg: "chore(deps): update dependencies"
          pr-body: |
            Automated `nix flake update`.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
